### ISSUE TITLE
Missing COMPATIBLE_MACHINE causes conflicts with other BSP's

### ISSUE THREAD

**Issue by WanWizard** [pli3/meta-qviart-5#9]
which also have a splash_bootlogo.bb recipe.

Please add:
````
COMPATIBLE_MACHINE = "lunix|lunix4k|lunix3_4k"
````
to address this issue.

https://github.com/pli3/meta-qviart-5/blob/a7a3ac2915fa6bbe29a2daa41de29c676e87378a/recipes-bsp/drivers/splash-bootlogo.bb#L6

**Comment by pli3** [comment]
added COMPATIBLE_MACHINE in splash-bootlogo.bb files.
